add strategy pattern
nastayda/patterns pull request #1
Opened 2020-03-05 09:27 UTC by adanilkina

2020-03-06 07:46 UTC, iriss22 requested changes

2020-03-06 07:46 UTC, iriss22 commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
а зачем тут абстрактные методы fight и move?
Какой смысл атаковать и идти без использования классов WeaponBehavior и SpeedBehavior?

2020-03-06 07:46 UTC, iriss22 commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
Почему protected WeaponBehavior weapon;
protected?

2020-03-06 07:46 UTC, iriss22 commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
и методы тоже

2020-03-09 17:56 UTC, nastayda commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
наверное чтобы реализовать в наследниках какоето действие с опреденным оружием `protected WeaponBehavior weapon;`  и `protected SpeedBehavior speed;` скоростью, удар с таким-то оружием и движение такое-то, для конкретно персонажа(например для King)

2020-03-09 18:01 UTC, nastayda commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
> Почему protected WeaponBehavior weapon;
> protected?

не знаю, можно и public 🙈

2020-03-10 08:54 UTC, iriss22 commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
ну у тебя же есть методы performWeapon и performSpeed, которые реализовывают конкретное действие с оружием и перемещение

2020-03-10 09:06 UTC, iriss22 commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
https://github.com/nastayda/patterns/pull/1#discussion_r389865927
почему public? стоит сделать private наоборот.
Всегда лучше писать код так, чтобы методы класса можно было менять только через геттеры и сеттеры. protected поля нужно делать, если доступ к ним нужен из наследника. Когда ты поле делаешь публичным, его может менять кто угодно как угодно и ты никак не можешь это контролировать.
Тут еще стоит подумать: может быть стоит сделать поля final. Если поле устанавливается 1 раз при создании и его никто не может понять во время выполнения, то лучше делать его final

2020-03-10 18:03 UTC, nastayda commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
> ну у тебя же есть методы performWeapon и performSpeed, которые реализовывают конкретное действие с оружием и перемещение

не, они же реализуют действие не конкретным оружием, а каким-то абстрактным(weapon типа WeaponBehavior который интерфейс общий для все реализаций типа KnifeBehavior и тд)

2020-03-10 18:10 UTC, nastayda commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
не получилось сделать private, в симуляторе используются эти методы

2020-03-11 14:04 UTC, iriss22 commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
у тебя сейчас немного странно получается: есть метод fight, который говорит просто, что герой сейчас будет атаковать, но при этом не атакует, т.к. ничего не знает об оружии и прочее. И есть метод performWeapon , который уже нормально атакует с использованием оружия. Вот с моем представлении метод fight не нужен. Нужен только метод атаки с применением оружия

2020-03-11 14:07 UTC, iriss22 commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
на счет protected и private полей. Лучше сделать private, и в классе Character  реализовать конструктор с двумя параметрами. Тем самым ты: даешь четкий контракт. Говоришь, что без оружия и типа хотьбы не возможно создать героя и тот кто придет дописывать код после тебя будет иметь меньше шансов ошибиться. Так же ты не даешь на ходу менять значения в этих полях, а если нужно будет менять на ходу, то это все равно легче делать через спец метод, чтобы потом легче в коде искать что и когда может поменять поведение атаки и хотьбы

2020-03-15 16:40 UTC, nastayda commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
да пожалуй согласна, что метод fight без применения оружия не нужен - уберу
с конструктором вроде поняла идею, тоже согласна, так будет лучше

про private так и не поняла... performWeapon не мжет быть private...

2020-03-16 08:29 UTC, iriss22 commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
я про приватные поля говорила (weapon и speed). Ты сейчас сделала их приватными

2020-03-16 08:30 UTC, iriss22 approved these changes

2020-03-16 18:02 UTC, nastayda commented on src/patterns/strategy/Character.java
> +import patterns.strategy.behavior.weapon.WeaponBehavior;
я все поняла)))

2020-03-16 18:24 UTC, merged